/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package worldmap;

import javax.swing.ImageIcon;
import level.properties.JFrame;

/**
 *
 * @author Bilgin
 */
public class map extends javax.swing.JFrame 
{

     String nameOfTheCity;

    /**
     * Creates new form map
     */
    public map() {
        this.setSize(800, 600);
        this.setResizable( false );
        initComponents();
    }

    /**
     * This method is called from withtin the constructor to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton3.setOpaque(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setBorderPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(860, 90, 110, 80);

        jButton4.setOpaque(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setBorderPainted(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(640, 330, 90, 60);

        jButton5.setOpaque(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setBorderPainted(false);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(60, 140, 100, 70);

        jButton6.setToolTipText("");
        jButton6.setOpaque(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setBorderPainted(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(670, 80, 100, 80);

        jButton7.setOpaque(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setBorderPainted(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(950, 290, 90, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldmap/Untitled.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 20, 130, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(880, 80, 130, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(650, 310, 90, 60);

        jLabel7.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("SYDNEY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(970, 330, 100, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(680, 73, 110, 60);

        jLabel9.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("WAIKIKI BEACH");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 190, 200, 24);

        jLabel10.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("HAGIA SOPHIA");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(670, 130, 180, 40);

        jLabel11.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("TABLE MOUNTAIN");
        jLabel11.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel11.setMinimumSize(new java.awt.Dimension(30, 30));
        jLabel11.setPreferredSize(new java.awt.Dimension(20, 30));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(630, 360, 200, 40);

        jLabel12.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(960, 270, 100, 70);

        jLabel13.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("FORBIDDEN CITY");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(870, 150, 200, 24);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(70, 120, 130, 70);

        jButton1.setOpaque(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setBorderPainted(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(530, 20, 100, 90);

        jLabel3.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("WESTMINSTER");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 80, 160, 40);

        jLabel6.setFont(new java.awt.Font("Utsaah", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("CHICHEN ITZA");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 170, 160, 24);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/soccer.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(240, 100, 110, 70);

        jButton2.setOpaque(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setBorderPainted(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(220, 120, 120, 80);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/worldmap/map.jpg"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 1060, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/westminster.png"));
        jLabel1.setIcon(II);
        jLabel3.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel1.setIcon(II);
        jLabel3.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/hagiasophia.png"));
        jLabel8.setIcon(II);
        jLabel10.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel8.setIcon(II);
        jLabel10.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/forbiddencity.png"));
        jLabel4.setIcon(II);
        jLabel13.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel4.setIcon(II);
        jLabel13.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/waikiki.png"));
        jLabel14.setIcon(II);
        jLabel9.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel14.setIcon(II);
        jLabel9.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/sydney.png"));
        jLabel12.setIcon(II);
        jLabel7.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel12.setIcon(II);
        jLabel7.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/tablemountain.png"));
        jLabel5.setIcon(II);
        jLabel11.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel5.setIcon(II);
        jLabel11.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        ImageIcon II = new ImageIcon(getClass().getResource("/images/chicenitza.png"));
        jLabel16.setIcon(II);
        jLabel6.setFont(new java.awt.Font("Utahh", 2, 20));
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        ImageIcon II = new ImageIcon(getClass().getResource("/images/soccer.png"));
        jLabel16.setIcon(II);
        jLabel6.setFont(new java.awt.Font("Utahh", 0, 14));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("waikikiBeach");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("chichenItza");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("westminster");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("hagiaSophia");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("forbiddenCity");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("tableMountain");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setVisible(true);
        frame.setCityName("sydneyOperaHouse");
    }//GEN-LAST:event_jButton7ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
